### ISSUE TITLE
Additon of Tag line, Testimonial CSS, and animation

### ISSUE THREAD

**Issue by Jakeman893** [Mad-Max-Fury-Code/ReliOx-Corp#21]
-Testimonial entries CSS: Only blue and green
-Original website animation needs to be present somewhere on the website (my vote is somewhere in the about me section)
-Tag line should be: "Advanced Green Chemistry for Extreme Odor Control"

**Comment by brysnave** [comment]
All done except for the animation. I don't know what animation you are talking about.

**Comment by Jakeman893** [comment]
I don't either, it was in the list of items from the slack lol
